<a href="https://colab.research.google.com/github/Rayers-Ranjitkar/Rayers_AI_Worksheets/blob/main/Worksheet1_Rayers_Ranjitkar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

-------------------------------------------------
**Problem 1: Array Creation**
------------------------------------------------

In [ ]:
#1. Initialize an empty array with size 2X2.
import numpy as np
arr = np.empty((2,2) )
print(arr.shape)


(2, 2)


In [ ]:
# 2. Initialize an all one array with size 4X2.
import numpy as np
ones_arr = np.ones((4,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
filled_arr = np.full((2,2),7) #.empty,.ones and .full takes multiple parameters so, should put size inside (size)
print(filled_arr)

[[7 7]
 [7 7]]


In [ ]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np
given_arr = np.full((3,3),7)
zeros_arr = np.zeros_like(given_arr) #_like provides the dimensions of the array
print(zeros_arr)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#5 . Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np
given_arr = np.full((3,3),7)
ones_arr = np.ones_like(given_arr)
print(ones_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

import numpy as np
new_list = [1,2,3,4]
new_numpyArr = np.array(new_list)
print(type(new_numpyArr) )

<class 'numpy.ndarray'>


-------------------------------------------------------------------------
**Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:**
-------------------------------------------------------------------------


In [ ]:
#1. Create an array with values ranging from 10 to 49.

import numpy as np
newArr = np.arange(10,50,1)
print(newArr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2 Create a 3X3 matrix with values ranging from 0 to 8.
import numpy as np
newMat = np.arange(0,9,1)
reshapedMat = newMat.reshape(3,3)
print(reshapedMat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
identityMat = np.eye(3,3 )
print(identityMat)

In [ ]:
#4. Create a random array of size 30 and find the mean of the array.

import numpy as np
randArr = np.arange(1,31,1)
sizedArr = randArr.reshape(10,3)
print (sizedArr)
print(f"The mean of the array is = {sizedArr.mean() }")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
The mean of the array is = 15.5


In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.

import numpy as np
randomArr = np.random.randint(0,9,size=(10,10) )
minValue = np.min(randomArr)
maxValue = np.max(randomArr)
print("Array: \n",randomArr)

print()
print("Minimum Value:",minValue)
print("Maximum Value:",maxValue)



Array: 
 [[0 2 0 2 4 3 0 5 7 6]
 [1 6 8 2 3 3 0 5 4 2]
 [3 4 7 8 6 4 0 0 1 7]
 [1 6 4 7 7 1 6 2 8 4]
 [1 4 7 5 1 7 1 1 5 5]
 [7 1 4 8 8 1 5 2 4 6]
 [4 5 4 0 2 0 0 2 4 1]
 [7 2 5 8 2 3 4 3 2 1]
 [6 6 8 6 1 8 8 7 8 1]
 [0 6 7 6 7 5 3 5 6 8]]

Minimum Value: 0
Maximum Value: 8


In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
zeroArr = np.zeros((5,2))
zeroArr[2,0] = 1

print(zeroArr)

[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#7 Reverse an array arr = [1,2,0,0,4,0].

import numpy as np
arr = np.array([1,2,0,0,4,0])
revArr = arr[::-1] #slicing

print(revArr)


[0 4 0 0 2 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.

import numpy as np
customizedArr = np.zeros((4,4))

customizedArr[0,:] = 1 #0th row, all col = top
customizedArr[:,0] = 1 #all row, 0th col = left
customizedArr[-1,: ] = 1 #last row, all col = last
customizedArr[:,-1 ] = 1 #all row, last col = right
print(customizedArr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

import numpy as np
customizedArr = np.zeros((8,8))

customizedArr[0,1::2] = 1
customizedArr[1,0::2] = 1
customizedArr[2,1::2] = 1
customizedArr[3,0::2] = 1
customizedArr[4,1::2] = 1
customizedArr[5,0::2] = 1
customizedArr[6,1::2] = 1
customizedArr[7,0::2] = 1

print(customizedArr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


-----------------------------------------
**Problem - 3: Array Operations**
-----------------------------------------

In [ ]:
#1. Adding arrays

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print()
print(v+w)


[[ 6  8]
 [10 13]]

[20 22]


In [ ]:
#2. Subracting arrays

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x-y)
print()
print(v-w)


[[-4 -4]
 [-4 -3]]

[-2 -2]


In [ ]:
# 3. Multiply the array with any integers of your choice

import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])

print(2*x)
print()
print(3*v)


[[ 2  4]
 [ 6 10]]

[27 30]


In [ ]:
# 4. Find the square of each element of the array.

import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])

print("The square of array X = \n",np.square(x))
print()
print("The square of array V = \n",np.square(v))
print()



The square of array X = 
 [[ 1  4]
 [ 9 25]]

The square of array V = 
 [ 81 100]



In [ ]:
 #5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print("The dot product between v and w =",np.dot(v,w))
print()
print("The dot product between = x and v\n",np.dot(x,v)) #numPy treats 1D vectors as column (or row) vectors depending on context to do matrix multiplication (here it used shape of v i.e. 2 as col vector to do  2x2 . 2x1). It could treat it as row vector too when necessary.
print()

print("The dot product between = x and y\n",np.dot(x,y))


The dot product between v and w = 219

The dot product between = x and v
 [29 77]

The dot product between = x and y
 [[19 22]
 [50 58]]


In [ ]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

Arr1Concat = np.concatenate((x,y), axis=1) #(axis-1 = col) = col with col = (col combine => horizontally) => (h-stack)
Arr1hStack = np.hstack((x,y) )
print("Concatenating x and y along row using concatenate: \n",Arr1Concat)
print("Concatenating x and y along row using hStack: \n",Arr1hStack)

#Arr2Concat = np.concatenate((v,w), axis=0) #(axis-0 = row) = row with row = (row combine = vertically) =>(v-stack)
Arr2vStack = np.vstack((v,w) )
#print("Concatenating v and w along row using concatenate: \n",Arr2Concat) #vstack always converts 1D arrays to 2D row vectors first (shape (1,n)), then stacks along axis=0 but concatenate doesn't so different result as concat just joins 1D array.
print("Concatenating v and w along row using vStack: \n",Arr2vStack)



Concatenating x and y along row using concatenate: 
 [[1 2 5 6]
 [3 5 7 8]]
Concatenating x and y along row using hStack: 
 [[1 2 5 6]
 [3 5 7 8]]
Concatenating v and w along row using vStack: 
 [[ 9 10]
 [11 12]]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

newArr = np.concatenate((x,v),axis=0)
#Dim of x = (2,2) and v = (2,) here,NumPy doesn’t automatically think of it as “row” or “column” — it’s just a flat array of length 2 and for multiplication:
#if it's axis=0 then it's stack row with row (v-stack) so, (Remaining axis i.e. column) column number should be same and vice versa but,
#Here, dimension of V is flat and there is no row and col so,error occurs. Moreover, Brodcasting only works with arithmentic operation (+,-,*,dot) if compatible.

----------------------------------------------------------
Problem-4. Matrix Operation
----------------------------------------------------------


In [ ]:
#1. Prove A.A−1 = I.

import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

A_inv = np.linalg.inv(A)
multipliedResult = np.dot(A,A_inv) #It's same as A @ A_inv

print(np.round(multipliedResult) )
isEqual = np.array_equal(np.round(multipliedResult),np.eye(2,2))
print("Multiplied result is identity: ",isEqual)



[[1. 0.]
 [0. 1.]]
Multiplied result is identity:  True


In [ ]:
#2. Prove AB̸=BA

import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

AB = A @ B
BA = B @ A
print("AB= \n",AB)
print("BA= \n",BA)

isEqual = np.array_equal(AB,BA)
print("Are AB and BA equal : ", isEqual)


AB= 
 [[23 13]
 [51 29]]
BA= 
 [[36 44]
 [13 16]]
Are AB and BA equal :  False


In [ ]:
#3. Prove (AB)T = BT AT.

import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

lhs = (A@B).T    #np.dot(A, B).T
rhs = (B.T @A.T) #np.dot(B.T, A.T)

print("LHS =\n", lhs)
print("RHS =\n", rhs)


isEqual = np.array_equal(lhs, rhs)
print("Are they equal? ->", isEqual)

LHS =
 [[23 51]
 [13 29]]
RHS =
 [[23 51]
 [13 29]]
Are they equal? -> True


In [ ]:
#4  Solve the following system of Linear equation using Inverse Methods.
 #2x −3y +z = −1
 #x −y +2z = −3
 #3x +y −z = 9

import numpy as np
A = np.array([ [2,-3,1],
               [1,-1,2],
               [3,1,-1]
               ] )
B = np.array([1,-3,9])

A_inv = np.linalg.inv(A)
X = A_inv @ B


print("The value of [x, y, z] = ", X)

The value of [x, y, z] =  [ 2.10526316  0.26315789 -2.42105263]


--------------------------------------------------------------------------------
4.2 How fast is numpy
--------------------------------------------------------------------------------

**4.2.1. Element-wise Addition:**

In [ ]:
# Using Python Lists, perform element-wise addition of two lists of size 1,000,000.
# Measure and Print the time taken for this operation.

import random
import time

size = 1000000
list1 = []
list2 = []
result = []

#Start
start_time = time.time()

for i in range(size):
  random_number = random.random()
  list1.append(random_number)

for i in range(size):
  random_number = random.random()
  list2.append(random_number)

for i in range(size):
  result.append(list1[i] +list2[i])

#End
end_time = time.time()

print(result[:10:1])

print("Time taken for normal addition", round(end_time - start_time,2), "sec")



[1.285304129507267, 0.7721700428113091, 0.8876115413365788, 1.0465134774809657, 0.586939581856685, 0.6484109129387087, 0.6477062949546618, 1.2087508600593537, 1.174848122115504, 0.09580233218722245]
Time taken for normal addition 0.55 sec


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

import random
import time
import numpy as np


size = 1000000
list1 = np.random.randint(0,100,size) #np.random.randint(low, high, size)
list2 = np.random.randint(0,100,size)

#Start
start_time = time.time()

result = list1 + list2

#End
end_time = time.time()

print(result[:10:1])

print("Time taken for numPy addition", round(end_time - start_time,2), "sec")

[111  65  40  95 145  85 120 119 105  42]
Time taken for numPy addition 0.0 sec


**4.2.2. Element-wise Multiplication:**

In [ ]:
#Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
# Measure and Print the time taken for this operation.

import random
import time

size = 1000000
list1 = []
list2 = []
result = []

#Start
start_time = time.time()

for i in range(size):
  random_number = random.random()
  list1.append(random_number)

for i in range(size):
  random_number = random.random()
  list2.append(random_number)

for i in range(size):
  result.append(list1[i] * list2[i])

#End
end_time = time.time()

print(result[:10:1])

print("Time taken for normal multiplication", round(end_time - start_time,2), "sec")

[0.08590674820477202, 0.47706728290471667, 0.17379482380963487, 0.4478157059131764, 0.48583648047145817, 0.4329640970139351, 0.25295683986083245, 0.14394837012957312, 0.24363212007622173, 0.46907187430723457]
Time taken for normal multiplication 0.56 sec


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

import random
import time
import numpy as np


size = 1000000
list1 = np.random.randint(0,100,size) #np.random.randint(low, high, size)
list2 = np.random.randint(0,100,size)

#Start
start_time = time.time()

result = list1 * list2

#End
end_time = time.time()

print(result[:10:1])

print("Time taken for numPy multiplication", round(end_time - start_time,2), "sec")

[6396 1312  316  144 1917 3672  244  546   96  902]
Time taken for numPy multiplication 0.02 sec


**4.2.3. Dot-product**

In [ ]:
#Using Python Lists, compute the dot product of two lists of size 1,000,000.
#Measure and Print the time taken for this operation.

import random
import time

size = 1000000
list1 = []
list2 = []
result = []

#Start
start_time = time.time()

for i in range(size):
  random_number = random.random()
  list1.append(random_number)

for i in range(size):
  random_number = random.random()
  list2.append(random_number)

dotProduct = 0
for i in range(size):
  dotProduct = dotProduct + (list1[i] *list2[i])

#End
end_time = time.time()

print("Dot-product = ",dotProduct)

print("Time taken for normal dot-product", round(end_time - start_time,2), "sec")


Dot-product =  249905.82073066354
Time taken for normal dot-product 0.84 sec


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

import random
import time
import numpy as np


size = 1000000
list1 = np.random.randint(0,100,size) #np.random.randint(low, high, size)
list2 = np.random.randint(0,100,size)

#Start
start_time = time.time()

result = np.dot(list1,list2)

#End
end_time = time.time()

print("Dot-product = ",result)

print("Time taken for numPy dot-product", round(end_time - start_time,2), "sec")

Dot-product =  2450161602
Time taken for numPy dot-product 0.0 sec


**4.2.3. Matrix-Multiplication**

In [ ]:
#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000.
#Measure and print the time taken for this operation.

import random
import time

size = 1000
matrix1 = []
matrix2 = []
result = []

# Start
start_time = time.time()

# Generating two 1000x1000 matrix
for i in range(size):
    row = []
    for j in range(size):
        row.append(random.randint(0, 9))  # integers 0-9
    matrix1.append(row)

for i in range(size):
    row = []
    for j in range(size):
        row.append(random.randint(0, 9))
    matrix2.append(row)

# creating 1000x1000 result matrix
for i in range(size):
    row = []
    for j in range(size):
        row.append(0)
    result.append(row)

# performing matrix multiplication
for i in range(size): #track of current row
    for j in range(size): #track of current col
        for k in range(size): #to iterate over each element (makes each row x each col possible)
            result[i][j] += matrix1[i][k] * matrix2[k][j]

# End
end_time = time.time()

# Printing first result stored in (0,0)
print("Result[0][0] =", result[0][0])
print("Time taken for normal matrix multiplication:", round(end_time - start_time, 2), "sec")



Result[0][0] = 19778
Time taken for normal matrix multiplication: 285.66 sec


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation

import numpy as np
import time

size = 1000

matrix1 = np.random.randint(0, 10, (size, size)) #np.random.randint(lowValue,highValue,size)
matrix2 = np.random.randint(0, 10, (size, size))

#Start
start_time = time.time()

result = np.dot(matrix1, matrix2)   # or, result = matrix1 @ matrix2

end_time = time.time()

# Printing first result stored in (0,0)
print("Result[0][0] =", result[0, 0])
print("Time taken for NumPy matrix multiplication:", round(end_time - start_time, 2), "sec")



Result[0][0] = 19422
Time taken for NumPy matrix multiplication: 1.38 sec
